# Generated by Django 4.2.13 on 2025-09-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExoplanetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('orbital_period', models.FloatField()),
                ('transit_duration', models.FloatField()),
                ('planet_radius', models.FloatField()),
                ('stellar_temp', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField(blank=True, null=True)),
                ('model_name', models.CharField(default='RandomForest', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
